version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "8000:8000"
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27107:27107"